verbose = true
no_progress = true
max_concurrency = 8
timeout = 15
retry_wait_time = 2
retry_count = 2

# приемаме редиректи/ограничения
accept = [200, 206, 301, 302, 307, 308, 401, 403, 429]

# не сканираме e-mail/localhost/file:
exclude = ["mailto:.*", "file:.*", "https?://localhost.*", "http://127\\.0\\.0\\.1.*"]

# двоични/несканируеми
exclude_path = ["docs/budget.xlsx"]
