blank_issues_enabled: false
contact_links:
  - name: Security disclosure
    url: https://github.com/forrybg/foritech-investor-demo/security/policy
    about: Please report security issues responsibly.
