
name: asciicast2gif
on:
  # Ръчно пускане от Actions
  workflow_dispatch:
  # Авто при промяна на .cast файла
  push:
    paths:
      - 'docs/assets/*.cast'

permissions:
  contents: write

jobs:
  build-gif:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List assets (pre)
        run: ls -la docs/assets || true

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert cast -> gif
        if: ${{ hashFiles('docs/assets/demo.cast') != '' }}
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/asciinema/asciicast2gif:latest
          options: -v ${{ github.workspace }}/docs/assets:/data -w /data
          run: |
            asciicast2gif -S 2 demo.cast demo.gif

      - name: Verify outputs
        run: |
          test -s docs/assets/demo.gif
          ls -lh docs/assets/demo.gif

      - name: Commit GIF (if changed)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update demo GIF (auto)"
          file_pattern: docs/assets/demo.gif
