name: asciicast2gif
on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/assets/*.cast'

permissions:
  contents: write

jobs:
  build-gif:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build converter image (from source)
        run: |
          docker build -t local/asciicast2gif 'https://github.com/asciinema/asciicast2gif.git#master'

      - name: Convert cast -> gif
        run: |
          test -s docs/assets/demo.cast
          docker run --rm -v "$PWD/docs/assets:/data" -w /data local/asciicast2gif \
            -S 2 demo.cast demo.gif
          ls -lh docs/assets/demo.gif

      - name: Commit GIF (if changed)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update demo GIF (auto)"
          file_pattern: docs/assets/demo.gif
