name: CI (lite)
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install deps
        run: |
          python -m pip install -U pip wheel
          if [ -f sdk/requirements.txt ]; then pip install -r sdk/requirements.txt || true; fi
          pip install pytest
      - name: Run pytest (allow missing OQS)
        run: |
          if [ -d tests ]; then pytest -q || true; else echo "No tests"; fi
