name: Docs link check
on:
  push:
    branches: [ docs-pack, main ]
    paths: [ 'docs/**', 'README.md' ]
  pull_request:
    branches: [ main ]
    paths: [ 'docs/**', 'README.md' ]
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress README.md docs
