name: Docs link check
on:
  pull_request:
    paths: ["docs/**", "README.md"]
  workflow_dispatch:
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with: { args: --verbose --no-progress --exclude-mail 'docs/** README.md' }
