name: Docs link check

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'README.md'

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lychee link check
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --config .lychee.toml docs/**/*.md README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
