name: Docs markdownlint
on:
  pull_request:
    paths: ["docs/**", "README.md", ".markdownlint.json"]
  push:
    branches: [ main ]
    paths: ["docs/**", "README.md", ".markdownlint.json"]
jobs:
  mdlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            README.md
            docs/**/*.md
          config: .markdownlint.json
