name: Release ZIP (docs)
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  zip-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pack investor docs
        run: |
          set -euo pipefail
          mkdir -p dist
 chore/release-rolling-tag
          # правим архива (LICENSE е опционален)
          zip -r dist/foritech-investor-pack.zip docs README.md
          if [ -f LICENSE ]; then zip -u dist/foritech-investor-pack.zip LICENSE; fi
          # fail ако няма/празен
=======
          zip -r dist/foritech-investor-pack.zip docs README.md
          if [ -f LICENSE ]; then zip -u dist/foritech-investor-pack.zip LICENSE; fi
main
          test -s dist/foritech-investor-pack.zip
          ls -lh dist

      - name: Compute rolling tag
        id: tag
        run: echo "TAG=docs-pack-$(date +%Y%m%d-%H%M%S)" >> "$GITHUB_OUTPUT"

      - name: Publish GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.TAG }}
          name: Investor Pack
          artifacts: dist/foritech-investor-pack.zip
          allowUpdates: false
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}
